<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "locallang_tools"
 *
 * Auto generated by Extension Builder 2016-02-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Locallang tools',
	'description' => 'Locallang tools',
	'category' => 'plugin',
	'author' => 'R3 H6',
	'author_email' => 'r3h6@outlook.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);